// <auto-generated />
using System;
using FinTrack.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinTrack.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FinTrackDbContext))]
    [Migration("20250915010300_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FinTrack.Core.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("USD");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("SyncStatus");

                    b.HasIndex("Type");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0m,
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Default checking account",
                            InitialBalance = 0m,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Primary Checking",
                            SyncId = "default-account-1",
                            SyncStatus = 0,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AlertThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SpentAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Period");

                    b.HasIndex("StartDate", "EndDate");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("SyncStatus");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("CategoryType");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsSystem");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("SortOrder");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("SyncStatus");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = 1,
                            Color = "#FF6B6B",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "restaurant",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Food & Dining",
                            SortOrder = 1,
                            SyncId = "category-expense-1",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = 1,
                            Color = "#4ECDC4",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "car",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Transportation",
                            SortOrder = 2,
                            SyncId = "category-expense-2",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = 1,
                            Color = "#45B7D1",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "shopping_cart",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Shopping",
                            SortOrder = 3,
                            SyncId = "category-expense-3",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 4,
                            CategoryType = 1,
                            Color = "#96CEB4",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "movie",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Entertainment",
                            SortOrder = 4,
                            SyncId = "category-expense-4",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 5,
                            CategoryType = 1,
                            Color = "#FFEAA7",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "receipt",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Bills & Utilities",
                            SortOrder = 5,
                            SyncId = "category-expense-5",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 6,
                            CategoryType = 1,
                            Color = "#DDA0DD",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "medical_services",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Healthcare",
                            SortOrder = 6,
                            SyncId = "category-expense-6",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 7,
                            CategoryType = 1,
                            Color = "#98D8C8",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "school",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Education",
                            SortOrder = 7,
                            SyncId = "category-expense-7",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 8,
                            CategoryType = 1,
                            Color = "#F7DC6F",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "flight",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Travel",
                            SortOrder = 8,
                            SyncId = "category-expense-8",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 9,
                            CategoryType = 1,
                            Color = "#BB8FCE",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "spa",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Personal Care",
                            SortOrder = 9,
                            SyncId = "category-expense-9",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 10,
                            CategoryType = 1,
                            Color = "#BDC3C7",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "more_horiz",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Other Expenses",
                            SortOrder = 10,
                            SyncId = "category-expense-10",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 11,
                            CategoryType = 0,
                            Color = "#2ECC71",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "work",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Salary",
                            SortOrder = 1,
                            SyncId = "category-income-1",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 12,
                            CategoryType = 0,
                            Color = "#27AE60",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "laptop",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Freelance",
                            SortOrder = 2,
                            SyncId = "category-income-2",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 13,
                            CategoryType = 0,
                            Color = "#16A085",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "trending_up",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Investment Returns",
                            SortOrder = 3,
                            SyncId = "category-income-3",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 14,
                            CategoryType = 0,
                            Color = "#1ABC9C",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "business",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Business Income",
                            SortOrder = 4,
                            SyncId = "category-income-4",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 15,
                            CategoryType = 0,
                            Color = "#58D68D",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "card_giftcard",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Gifts & Bonuses",
                            SortOrder = 5,
                            SyncId = "category-income-5",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        },
                        new
                        {
                            Id = 16,
                            CategoryType = 0,
                            Color = "#82E0AA",
                            CreatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Icon = "attach_money",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Other Income",
                            SortOrder = 6,
                            SyncId = "category-income-6",
                            SyncStatus = 0,
                            UpdatedAt = new DateTime(2025, 9, 15, 1, 3, 0, 0, DateTimeKind.Utc),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinkedAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LinkedAccountId");

                    b.HasIndex("Priority");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("SyncStatus");

                    b.HasIndex("TargetDate");

                    b.HasIndex("Type");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.GoalMilestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SortOrder");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("SyncStatus");

                    b.HasIndex("TargetDate");

                    b.ToTable("GoalMilestones");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.HasIndex("Date", "AccountId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SyncId")
                        .IsUnique();

                    b.HasIndex("SyncStatus");

                    b.HasIndex("Type");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Budget", b =>
                {
                    b.HasOne("FinTrack.Core.Entities.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Category", b =>
                {
                    b.HasOne("FinTrack.Core.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Goal", b =>
                {
                    b.HasOne("FinTrack.Core.Entities.Account", "LinkedAccount")
                        .WithMany("Goals")
                        .HasForeignKey("LinkedAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedAccount");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.GoalMilestone", b =>
                {
                    b.HasOne("FinTrack.Core.Entities.Goal", "Goal")
                        .WithMany("Milestones")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Transaction", b =>
                {
                    b.HasOne("FinTrack.Core.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinTrack.Core.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Account", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("SubCategories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinTrack.Core.Entities.Goal", b =>
                {
                    b.Navigation("Milestones");
                });
#pragma warning restore 612, 618
        }
    }
}