name: Build & Deploy Go App

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22' # Change to your Go version

    - name: Build Go App
      run: |
        cd backend/go
        go build -o app .

    - name: Upload binary to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT || '22' }}
        key: ${{ secrets.SSH_KEY }}
        source: "backend/go/app"
        target: ${{ secrets.DEPLOY_PATH }}

    - name: SSH into server and restart service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT || '22' }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo systemctl stop fintrack
          mv ${{ secrets.DEPLOY_PATH }}/app /usr/local/bin/fintrack
          sudo systemctl start fintrack
          sudo systemctl status fintrack --no-pager
